Repository mmoizhussain/riscv-sbi-basic, pull requests merged in 2022-04, with the labels that each got.

#22 Danish/issue#09
  code/include/env/mcause.h
  code/include/env/mcounteren.h
  code/include/env/mcountinhibit.h
  code/include/env/menvcfg.h
  code/include/env/mseccfg.h
Labels: enhancement

#15 Hassan/issue#8
  code/include/env/medeleg.h
  code/include/env/mideleg.h
  code/include/env/mie.h
  code/include/env/mip.h
  code/include/env/mtvec.h
  code/include/env/stvec.h
Labels: good first issue

#29 Rabianoor/issue#6
  code/include/env/mstatus.h
  code/include/env/mstatush.h
  code/include/env/sstatus.h
Labels: good first issue

#33 Updated_Extensions_for_misa_Table3.2
  code/include/env/misa.h
Labels: help wanted

#53 Issue#36/sbi spec 3.6,3.7
  code/src/test/test__sbi_get_marchid/test__sbi_get_marchid.c
  code/src/test/test__sbi_get_mimpid/test__sbi_get_mimpid.c
  testlists/test__sbi_get_marchid.sh
  testlists/test__sbi_get_mimpid.sh
Labels: enhancement

#44 implemented sbi testcases for sbi spec section 3.5
  code/src/test/test__sbi_get_mvendorid/test__sbi_get_mvendorid.c
  testlists/test__sbi_get_mvendorid.sh
Labels: good first issue

#49 Implemented testcases for sbi spec section 3.4
  code/src/test/test__sbi_probe_extension/test__sbi_probe_extension.c
  testlists/test__sbi_probe_extension.sh
Labels: good first issue

#57 test for section 4.1
  code/src/test/test_sbi_set_timer/test_sbi_set_timer.c
  testlists/test__sbi_set_timer.sh
Labels: good first issue

#60 issue # 52: tests for section 4.6, 4.7, 4.8
  code/src/test/test__sbi_remote_fence_i/test__sbi_remote_fence_i.c
  code/src/test/test__sbi_remote_sfence_vma/test__sbi_remote_sfence_vma.c
  code/src/test/test__sbi_remote_sfence_vma_asid/test__sbi_remote_sfence_vma_asid.c
  testlists/test__sbi_remote_fence_i.sh
  testlists/test__sbi_remote_sfence_vma.sh
  testlists/test__sbi_remote_sfence_vma_asid.sh
Labels: bug
